eigent-ai/eigent

backend/app/service/chat_service.py

when decompose task ，can‘t notice budget not enough

fix: when decompose task ，can‘t notice budget not enough

---

backend/uv.lock
electron/main/init.ts
package.json
src/components/InstallStep/InstallDependencies.tsx
src/components/Toast/creditsToast.tsx
src/components/Toast/storageToast.tsx
src/pages/Login.tsx
src/pages/SignUp.tsx

feat: add timezone-based proxy configuration and fix minor issues

---

src/pages/Setting/Models.tsx

feat: add support for new model

---

backend/app/__init__.py
backend/pyproject.toml
backend/uv.lock

improve: remove unuse dependency

---

src/pages/Setting/Models.tsx
src/store/authStore.ts

Fix model name

---

src/pages/Setting/Models.tsx

fix: correct API URL handling for custom model

---

backend/app/component/model_validation.py
backend/app/model/chat.py
backend/app/utils/agent.py
backend/uv.lock
src/lib/llm.ts
src/store/chatStore.ts

chore: fix openai_compatible_model check

---

electron-builder.json

improve: package remove gif and mp4

---

backend/pyproject.toml
backend/uv.lock
electron/main/init.ts
package.json

Feat auto kill on restart

---

src/components/ChatBox/TaskCard.tsx

fix: refine TaskCard height display to resolve overflow issue

---

backend/app/__init__.py
electron/main/init.ts
electron/main/utils/process.ts

1. There are cors error in some machine， add cors middleware
2. Some user's cache folder was sudo create, this will make eigent can't write cache, change default cache folder and uv cache

fix: avoid cors error, avoid permission folder error

---

electron/main/init.ts
package.json

Fix install mirror proxy

---

src/pages/Setting/Models.tsx

chore: FIx local model verfiy

---

src/pages/Setting/Models.tsx

chore: model url validation

---

src/store/chatStore.ts

fix: correct screenshot migration address handling

---

backend/app/utils/agent.py
backend/pyproject.toml
backend/uv.lock

fix: unsupported model config

---

.env.development
package.json
src/components/Toast/creditsToast.tsx
src/components/Toast/storageToast.tsx
src/components/Toast/trafficToast.tsx
src/components/TopBar/index.tsx
src/pages/Setting/Models.tsx
src/pages/SignUp.tsx
src/store/chatStore.ts

fix(ui): fix alignment and spacing issues

---

backend/app/component/model_validation.py
backend/app/controller/model_controller.py

chore: ehance verify prompt

---

backend/app/utils/agent.py
backend/app/utils/toolkit/openai_image_toolkit.py

if user use cloud key, then can use openaiimage

feat: add openai image toolkit support

---

backend/app/utils/toolkit/notion_mcp_toolkit.py
electron/main/index.ts
electron/main/utils/envUtil.ts
package.json
src/App.tsx
src/components/AddWorker/IntegrationList.tsx
src/components/AddWorker/ToolSelect.tsx
src/components/InstallStep/InstallDependencies.tsx
src/components/TopBar/index.tsx
src/pages/Setting/MCP.tsx
src/pages/Setting/Models.tsx
src/pages/Setting/components/IntegrationList.tsx
src/store/authStore.ts
src/store/chatStore.ts

Fix notionmcp connet error

---

src/store/chatStore.ts

fix: correct model error in history record saving

---

.env.development
.gitignore
electron/main/index.ts
electron/main/init.ts
electron/main/utils/envUtil.ts
electron/main/utils/log.ts
electron/preload/index.ts
package.json
src/components/TopBar/index.tsx
src/lib/index.ts
src/store/chatStore.ts
vite.config.ts

Feature upload logs

---

electron/main/init.ts
src/pages/Home.tsx

Fix kill python process

---

README.md

Update contribution link in readme.md

fix:update readme contribution

---

src/components/WorkSpaceMenu/index.tsx
src/pages/Home.tsx

fix: webview not showing

---

.github/ISSUE_TEMPLATE/bug_report.yml
package.json

release: v 0.0.50

---

backend/app/utils/toolkit/openai_image_toolkit.py

fix: image naming

---

electron-builder.json

fix: exclude __pycache__ from build

---

.github/ISSUE_TEMPLATE/bug_report.yml
package.json

new version release

---

backend/app/utils/workforce.py

fix workforce

---

src/components/AddWorker/IntegrationList.tsx
src/components/AddWorker/ToolSelect.tsx
src/pages/Setting/MCP.tsx
src/pages/Setting/components/IntegrationList.tsx
src/pages/Setting/components/MCPList.tsx

chore: rename notion mcp to mcp market

---

.github/ISSUE_TEMPLATE/bug_report.yml
backend/pyproject.toml
backend/uv.lock
package.json

release: update camel version

---

docs/core/workers.md
docs/docs.json

chore: update doc

---

LICENSE

udpate license format

---

.github/workflows/build.yml

fix: cd uv dependency

---

src/pages/Login.tsx

fix: open model button when switching sign-in accounts (#228)

---

.github/ISSUE_TEMPLATE/bug_report.yml
package.json

release: v 0.0.60

---

server/.gitignore
server/README_CN.md
server/README_EN.md
server/uv.lock

chore: Self host updated 

---

src/components/ChatBox/index.tsx

fix: data privacy setting

---

src/components/ChatBox/index.tsx
src/pages/Setting/Privacy.tsx

chore: update Privacy page text content

---

src/components/Folder/index.tsx

enhance:navigation when opening output file from chat

---

src/components/Folder/index.tsx

fix: navigation when opening output file from chat ( #255)

---

.github/ISSUE_TEMPLATE/bug_report.yml
package.json

release: v 0.0.62

---

.github/ISSUE_TEMPLATE/bug_report.yml
package.json
src/store/chatStore.ts

fix: package json bug

---

src/components/ChatBox/index.tsx
src/store/chatStore.ts

enhance: error cancel loading PR273

---

electron/main/init.ts

enhance: find avaliable port PR274

---

src/components/Layout/index.tsx

enhance: Notification about closing windows PR275

---

backend/app/service/chat_service.py

fix: await usage

---

src/store/chatStore.ts

fix: task shown 2 times in the frontend

---

src/pages/Setting/Models.tsx

chore: update wording

---

backend/app/component/environment.py
backend/app/controller/chat_controller.py
backend/app/controller/task_controller.py
backend/app/utils/agent.py

chore: unify backend and front env logic

---

src/pages/Setting/MCP.tsx
src/pages/Setting/components/MCPList.tsx

enhance: PR 339 mcp config page

---

backend/app/utils/toolkit/slack_toolkit.py

chore: Slack enhance support file_path

---

src/i18n/index.ts
src/i18n/locales/index.ts

Pr feat sw

---

.github/workflows/build-view.yml

Test build

---

backend/app/utils/agent.py
src/components/ChatBox/BottomInput.tsx
src/components/ChatBox/index.tsx
src/i18n/locales/en-us/setting.json
src/pages/Setting/Models.tsx

feat: make google search and engin id optional

---

src/components/ChatBox/TaskCard.tsx
src/store/chatStore.ts

fix(taskcard, workflow): resolve disagree status mismatch

---

src/components/AddWorker/IntegrationList.tsx
src/components/AddWorker/ToolSelect.tsx
src/components/AddWorker/index.tsx
src/components/ChatBox/BottomInput.tsx
src/components/ui/tooltip.tsx
src/pages/Setting/MCPMarket.tsx
src/pages/Setting/components/MCPListItem.tsx
src/store/authStore.ts

1. Subscribe to required states only in Add Worker
2. Add functionality to tooltip icons
3. Fix sending "empty message" bug in Chatbox
4. Create TooltipSimple component & replace some

enhance: Add Worker, add simple tooltip and fix empty message bug

---

src/pages/Setting/components/MCPEnvDialog.tsx

enhance: Verify the validity of google and exa api PR377

---

.vscode/settings.json
src/pages/Setting/components/MCPEnvDialog.tsx

Verify the validity of google and exa api

Verify the validity of google and exa api

---

backend/pyproject.toml
backend/uv.lock

chore: update camel version

---

backend/app/controller/model_controller.py

Adjust the verification logic to conform to the order of #344  description.

Optimize model validate logic: Remove the preceding model name check

---

server/alembic/versions/2025_09_28_1621-d74ab2a44600_drop_mcp_user_foreign_key_constraint.py
server/app/model/mcp/mcp_user.py

Add alembic reversion to fix bug from #42

fix bug: remove table mcp_use's foreign key(mcp_id)

---

src/pages/Setting/Models.tsx
src/store/authStore.ts

change model PR420

---

src/pages/Setting/Models.tsx
src/store/authStore.ts

change model

---

src/pages/Setting/Models.tsx

Replace copy button with close button in validation error toast

enhance: Fix incorrect button position in model validation modal PR414

---

src/components/Layout/index.tsx
src/pages/Setting/Models.tsx

Fix incorrect button position in model validation modal

---

backend/app/component/command.py

fix: path issue

---

src/components/WorkFlow/index.tsx

fix: frontend share button

---

backend/app/utils/workforce.py
src/store/chatStore.ts

fix: Frontend Displays Empty Tasks – Investigation Needed issue 436

---

backend/app/service/chat_service.py

fix: ask remains “Running” after forced exit and reopening issue 434
